export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const FETCH_NEWS_START = 'FETCH_NEWS_START';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAILURE = 'FETCH_NEWS_FAILURE';